services:
  redis:
    image: redis:7-alpine
    container_name: nyx-redis
    restart: unless-stopped
    ports:
      - "6381:6379"

  postgres:
    image: postgres:16-alpine
    container_name: nyx-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nyx_db
      POSTGRES_USER: nyx_user
      POSTGRES_PASSWORD: nyx_password
    ports:
      - "7778:5432"
    volumes:
      - nyx_postgres_data:/var/lib/postgresql/data

volumes:
  nyx_postgres_data:
