# Generated by Django 6.1.1 on 2026-09-17 14:29

from django.db import migrations

ROLES = [
    ("superadmin", 1),
    ("dgp", 2),
    ("cp", 3),
    ("dsp", 4),
    ("inspector", 5),
]


def seed_roles(apps, schema_editor):
    Role = apps.get_model("roles", "Role")
    for name, level in ROLES:
        Role.objects.get_or_create(name=name, defaults={"level": level})


def unseed_roles(apps, schema_editor):
    Role = apps.get_model("roles", "Role")
    Role.objects.filter(name__in=[name for name, _ in ROLES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_roles, unseed_roles),
    ]
