# Generated by Django 6.1.1 on 2026-09-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
